# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: HA Box"
  org.opencontainers.image.description: "Interface physique pour Home Assistant avec écran E-Paper, capteurs et contrôleurs"
  org.opencontainers.image.source: "https://github.com/VOTRE_USERNAME/ha-box"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
