# https://developers.home-assistant.io/docs/apps/configuration
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: HA Box"
  org.opencontainers.image.description: "Physical interface for Home Assistant with E-Paper display, sensors and controllers"
  org.opencontainers.image.source: "https://github.com/VOTRE_USERNAME/ha-box"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2024.11.2"
